### ISSUE TITLE
UnicodeDecodeError on /en-US/search

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6042]
Traceback:
```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 3: invalid start byte
  File "django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "newrelic/hooks/framework_django.py", line 544, in wrapper
    return wrapped(*args, **kwargs)
  File "django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "ratelimit/decorators.py", line 30, in _wrapped
    return fn(*args, **kw)
  File "kuma/search/views.py", line 27, in search
    results = search_api(request, *args, **kwargs).data
  File "django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "newrelic/hooks/component_djangorestframework.py", line 46, in _nr_wrapper_APIView_dispatch_
    return wrapped(*args, **kwargs)
  File "rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "newrelic/hooks/component_djangorestframework.py", line 53, in _handle_exception_wrapper
    return wrapped(*args, **kwargs)
  File "rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "kuma/search/search.py", line 64, in list
    return super(SearchView, self).list(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "rest_framework/generics.py", line 180, in get_paginated_response
    return self.paginator.get_paginated_response(data)
  File "kuma/search/pagination.py", line 41, in get_paginated_response
    ('filters', self.view.get_filters(self.page.aggregations)),
  File "kuma/search/search.py", line 123, in get_filters
    return FacetedFilterSerializer(sorted_filters, many=True).data
  File "rest_framework/serializers.py", line 768, in data
    ret = super(ListSerializer, self).data
  File "rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "rest_framework/serializers.py", line 686, in to_representation
    self.child.to_representation(item) for item in iterable
  File "rest_framework/serializers.py", line 530, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "rest_framework/serializers.py", line 686, in to_representation
    self.child.to_representation(item) for item in iterable
  File "rest_framework/serializers.py", line 517, in to_representation
    attribute = field.get_attribute(instance)
  File "rest_framework/fields.py", line 453, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "rest_framework/fields.py", line 106, in get_attribute
    instance = instance()
  File "kuma/search/queries.py", line 15, in urls
    self.url.merge_query_param(self.group_slug, self.slug)),
  File "kuma/search/utils.py", line 40, in merge_query_param
    params = self.query.multi_dict
  File "urlobject/query_string.py", line 47, in multi_dict
    for name, value in self.list:
  File "urlobject/query_string.py", line 35, in list
    value = qs_decode(value)
  File "urlobject/query_string.py", line 138, in _qs_decode_py2
    return urllib.unquote_plus(s).decode('utf-8')
  File "encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
```

You can easily reproduce it by opening: https://developer.mozilla.org/en-US/search?q=%27%22%3C%ff/script111111

At the time of writing, it's only happened to 1 user 3 times. That's probably not a human but a bot. Either way, it shouldn't cause a ISE.

**Comment by peterbe** [comment]
Most likely, this'll resolve once we're in Python 3. Consider:

```python
from urlobject import URLObject

u = URLObject(u'http://mdn.localhost:8000/en-US/search?q=%27%22%3C%ff/script111111')
print(repr(u.query.multi_dict))
```
Run that in Kuma's python 2.7 and you get:
```
Traceback (most recent call last):
  File "dummy.py", line 13, in <module>
    u.query.multi_dict
  File "/usr/local/lib/python2.7/site-packages/urlobject/query_string.py", line 47, in multi_dict
    for name, value in self.list:
  File "/usr/local/lib/python2.7/site-packages/urlobject/query_string.py", line 35, in list
    value = qs_decode(value)
  File "/usr/local/lib/python2.7/site-packages/urlobject/query_string.py", line 145, in _qs_decode_py2
    return urllib.unquote_plus(s).decode('utf-8')
  File "/usr/local/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 3: invalid start byte
```

Do the same in Python 3.7 and you get:
```
{'q': ['\'"<�/script111111']}
```

**Comment by peterbe** [comment]
No longer happens because we use Python 3 now.
