### ISSUE TITLE
Logging problems with Celery when running Python 3 on stage

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6097]
**Summary**
When https://github.com/mdn/kuma/pull/6084 was deployed to stage, we saw the following errors on the Celery beat and worker pods:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1186, in __repr__
    level = getLevelName(self.level)
AttributeError: 'WatchedFileHandler' object has no attribute 'level'
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 416, in execute
    return cls(
  File "/usr/local/lib/python3.8/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/bin/worker.py", line 252, in run
    worker = self.app.Worker(
  File "/usr/local/lib/python3.8/site-packages/celery/worker/worker.py", line 101, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/local/lib/python3.8/site-packages/celery/worker/worker.py", line 134, in setup_instance
    self.on_init_blueprint()
  File "/usr/local/lib/python3.8/site-packages/celery/apps/worker.py", line 120, in on_init_blueprint
    self._custom_logging = self.setup_logging()
  File "/usr/local/lib/python3.8/site-packages/celery/apps/worker.py", line 165, in setup_logging
    return self.app.log.setup(
  File "/usr/local/lib/python3.8/site-packages/celery/app/log.py", line 67, in setup
    handled = self.setup_logging_subsystem(
  File "/usr/local/lib/python3.8/site-packages/celery/app/log.py", line 114, in setup_logging_subsystem
    self._configure_logger(
  File "/usr/local/lib/python3.8/site-packages/celery/app/log.py", line 152, in _configure_logger
    self.setup_handlers(logger, logfile, format,
  File "/usr/local/lib/python3.8/site-packages/celery/app/log.py", line 218, in setup_handlers
    handler = self._detect_handler(logfile)
  File "/usr/local/lib/python3.8/site-packages/celery/app/log.py", line 228, in _detect_handler
    return WatchedFileHandler(logfile)
  File "/usr/local/lib/python3.8/logging/handlers.py", line 435, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 29] Illegal seek
```

**Expected behavior**
No errors

**Additional context**
This is within the context of moving from Python 2 to Python 3.

**Comment by escattone** [comment]
@callahad Discovered the fix for these errors. Here's what he said within a DM Slack channel:
```
Here's the deal: We're launching Celery (both worker and beat) with --logfile=/dev/stdout. We can't do that on Linux with Python 3.
To reproduce the crash, run python3 -c "from logging import FileHandler; FileHandler('/dev/stdout')"
We need to be using a StreamHandler instead, but there's no command-line way to tell Celery to do that.
(Celery decides between StreamHandler and WatchedFileHandler based on whether or not logfile has a .write() attribute -- basically, is logfile a file path or an opened Stream object)
But we can only pass strings to --logfile, so we always get the WatchedFileHandler
(Which seems fine on macOS, but blows up on Linux, as mentioned above)
So how do we fix it? If you don't pass --logfile at all, Celery logs to stderr.
So we just need to make it OK that our Celery logs are going to stderr instead of stdout, drop the --logfile arg, and we should be grand!
I don't know the first thing about Kubernetes, but I know you'll have to modify (at least) these two files: https://github.com/mdn/infra/blob/master/apps/mdn/mdn-aws/k8s/celery.beat.deploy.yaml.j2 and https://github.com/mdn/infra/blob/master/apps/mdn/mdn-aws/k8s/celery.workers.deploy.yaml.j2
```
