### ISSUE TITLE
[Django 2]: Test failures: Cannot encode None as POST data

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6566]
> Blocks: #6172 (Upgrade to Django 2)

Three of our tests fail under Django 2 with:

```
_____________________________ test_user_edit_beta ______________________________
Traceback (most recent call last):
  File "/app/kuma/users/tests/test_views.py", line 924, in test_user_edit_beta
    response = user_client.post(url, form)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 543, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 354, in post
    post_data = self._encode_data(data, content_type)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 313, in _encode_data
    return encode_multipart(BOUNDARY, data)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 196, in encode_multipart
    raise TypeError(
TypeError: Cannot encode None as POST data. Did you mean to pass an empty string or omit the value?
___________________________ test_user_edit_websites ____________________________
Traceback (most recent call last):
  File "/app/kuma/users/tests/test_views.py", line 958, in test_user_edit_websites
    response = user_client.post(url, form, follow=True)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 543, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 354, in post
    post_data = self._encode_data(data, content_type)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 313, in _encode_data
    return encode_multipart(BOUNDARY, data)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 196, in encode_multipart
    raise TypeError(
TypeError: Cannot encode None as POST data. Did you mean to pass an empty string or omit the value?
_______________________ test_user_edit_github_is_public ________________________
Traceback (most recent call last):
  File "/app/kuma/users/tests/test_views.py", line 1019, in test_user_edit_github_is_public
    response = user_client.post(url, form)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 543, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 354, in post
    post_data = self._encode_data(data, content_type)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 313, in _encode_data
    return encode_multipart(BOUNDARY, data)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 196, in encode_multipart
    raise TypeError(
TypeError: Cannot encode None as POST data. Did you mean to pass an empty string or omit the value?
```

This is because Django's test client now raises an exception when asked to serialize `None` values. See https://code.djangoproject.com/ticket/30024 and https://docs.djangoproject.com/en/2.2/topics/testing/tools/#django.test.Client.post.

For example, in the first case, the form data we're trying to POST is:

```
{'user-beta': True,
 'user-country': 'us',
 'user-format': 'html',
 'user-fullname': None,
 'user-irc_nickname': None,
 'user-is_github_url_public': False,
 'user-location': None,
 'user-organization': None,
 'user-title': None,
 'user-username': 'wiki_user'}
```

From what I've read, earlier versions of Django would coerce `None` to a String, `"None"`, which is almost certainly incorrect.

Potential solutions:

1. Set the `None` values to something valid, potentially just the empty string.
2. Filter out all keys with `None` values
3. POST the form as `application/json` and not as `multipart/form-data`, since JSON _does_ have a `null` data type

**Comment by callahad** [comment]
Filtering out keys with `None` as their value works here. Removing blocker label.
