### ISSUE TITLE
[Django 2]: Test failures: User.has_usable_password() unexpectedly True

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6567]
> Blocks: #6172 (Upgrade to Django 2)

Two of our tests fail under Django 2 with:

```
______________________________ test_recover_valid ______________________________ 
Traceback (most recent call last):                                               
  File "/app/kuma/users/tests/test_views.py", line 1710, in test_recover_valid   
    assert not wiki_user.has_usable_password()                                   
AssertionError: assert not True                                                  
 +  where True = <bound method AbstractBaseUser.has_usable_password of <User: wiki_user>>()
 +    where <bound method AbstractBaseUser.has_usable_password of <User: wiki_user>> = <User: wiki_user>.has_usable_password
________________ TestUser.test_get_recovery_url_blank_password _________________ 
Traceback (most recent call last):                                               
  File "/app/kuma/users/tests/test_models.py", line 114, in test_get_recovery_url_blank_password
    assert not user.has_usable_password()                                        
AssertionError: assert not True                                                  
 +  where True = <bound method AbstractBaseUser.has_usable_password of <User: testuser>>()
 +    where <bound method AbstractBaseUser.has_usable_password of <User: testuser>> = <User: testuser>.has_usable_password
```

I have not yet investigated the cause, but effectively `User.has_usable_password()` is `True` in cases where it shouldn't be.

**Comment by callahad** [comment]
Okay, so the behavior of `User.has_usable_password()` changed in Django 2.1:

> In older versions, this also returns False if the password is None or an empty string, or if the password uses a hasher that’s not in the PASSWORD_HASHERS setting. That behavior is considered a bug as it prevents users with such passwords from requesting a password reset.

https://docs.djangoproject.com/en/2.2/ref/contrib/auth/#django.contrib.auth.models.User.has_usable_password

**Comment by callahad** [comment]
The [release notes](https://docs.djangoproject.com/en/2.2/releases/2.1/#miscellaneous) specifically state:

> `User.has_usable_password()` and the `is_password_usable()` function no longer return `False` if the password is `None` or an empty string, or if the password uses a hasher that’s not in the `PASSWORD_HASHERS` setting. This undocumented behavior was a regression in Django 1.6 and prevented users with such passwords from requesting a password reset. Audit your code to confirm that your usage of these APIs don’t rely on the old behavior.

We do not use `has_usable_password` outside of test functions, we do not use `is_password_usable` anywhere. We do not call `User.set_password` outside of test / management functions, either. Or unused templates for password reset. Which we should probably remove.

Still need to dig a little deeper, but this looks like it should be a quick fix.

**Comment by callahad** [comment]
I've got this resolved in my branch, dropping the blocker flag.
