### ISSUE TITLE
Unable to translate 'Web/HTTP/Overview' to Turkish

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6766]
https://sentry.prod.mozaws.net/operations/mdn-prod/issues/7440553/

```
Resolver404: {'tried': [[<URLPattern '^media/(?:redesign/)?css/(?P<doc>.*)-min.css$'>], [<URLPattern '^media/(?:redesign/)?js/(?P<doc>.*)-min.js$'>], [<URLPattern '^media/(?:redesign/)?img(?P<suffix>.*)$'>], [<URLPattern '^media/(?:redesign/)?css(?P<suffix>.*)$'>], [<URLPattern '^media/(?:redesign/)?js(?P<suffix>.*)$'>], [<URLPattern '^media/(?:redesign/)?fonts(?P<suffix>.*)$'>], [<URLPattern '^media/uploads/demos/(?:.*)$'>], [<URLPattern '(?i)^(?P<one>.*)//(?P<two>.*)//(?P<three>.*)$'>], [<URLPattern '(?i)^(?P<one>.*)//(?P<two>.*)$'>], [<URLPattern '(?i)^samples/canvas-tutorial/2_1_canvas_rect.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/2_2_canvas_moveto.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/2_3_canvas_lineto.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/2_4_canvas_arc.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/2_5_canvas_quadraticcurveto.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/2_6_canvas_beziercurveto.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/3_1_canvas_drawimage.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/3_2_canvas_drawimage.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/3_3_canvas_drawimage.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/3_4_canvas_gallery.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_1_canvas_fillstyle.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_2_canvas_strokestyle.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_3_canvas_globalalpha.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_4_canvas_rgba.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_5_canvas_linewidth.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_6_canvas_linecap.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_7_canvas_linejoin.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_8_canvas_miterlimit.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_9_canvas_lineargradient.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_10_canvas_radialgradient.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_11_canvas_createpattern.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/5_1_canvas_savestate.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/5_2_canvas_translate.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/5_3_canvas_rotate.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/5_4_canvas_scale.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/6_1_canvas_composite.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/6_2_canvas_clipping.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/globalCompositeOperation.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/backdrop.png$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/bg_gallery.png$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_1.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_2.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_3.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_4.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_5.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_6.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_7.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_8.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/picture_frame.png$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/rhino.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/wallpaper.png$'>], [<URLPattern '(?i)^samples/domref/mozGetAsFile.html$'>], [<URLPattern '(?i)^samples/raycaster/input.js$'>], [<URLPattern '(?i)^samples/raycaster/Level.js$'>], [<URLPattern '(?i)^samples/raycaster/Player.js$'>], [<URLPattern '(?i)^samples/raycaster/RayCaster.html$'>], [<URLPattern '(?i)^samples/raycaster/RayCaster.js$'>], [<URLPattern '(?i)^samples/raycaster/trace.css$'>], [<URLPattern '(?i)^samples/raycaster/trace.js$'>], [<URLPattern '(?i)^samples/webgl/sample1$'>], [<URLPattern '(?i)^samples/webgl/sample1/index.html$'>], [<URLPattern '(?i)^samples/webgl/sample1/webgl-demo.js$'>], [<UR...
  File "redirect_urls/middleware.py", line 14, in __call__
    resolver_match = self.resolver.resolve(request.path_info)
  File "newrelic/hooks/framework_django.py", line 600, in wrapper
    return _wrapped(*args, **kwargs)
  File "newrelic/hooks/framework_django.py", line 588, in _wrapped
    result = wrapped(path)
  File "django/urls/resolvers.py", line 567, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})

IntegrityError: (1062, "Duplicate entry '192533-tr' for key 'wiki_document_parent_id_1890db2968e98804_uniq'")
(1 additional frame(s) were not displayed)
...
  File "django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "newrelic/hooks/database_dbapi2.py", line 24, in execute
    return self.__wrapped__.execute(sql, parameters,
  File "MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)

IntegrityError: (1062, "Duplicate entry '192533-tr' for key 'wiki_document_parent_id_1890db2968e98804_uniq'")
(30 additional frame(s) were not displayed)
...
  File "django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "newrelic/hooks/database_dbapi2.py", line 24, in execute
    return self.__wrapped__.execute(sql, parameters,
  File "MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)

IntegrityError: (1062, "Duplicate entry '192533-tr' for key 'wiki_document_parent_id_1890db2968e98804_uniq'")
```

**Comment by peterbe** [comment]
It is most likely not specific with `Web/HTTP/Overview` and `tr` (Turkish) but the problem is apparent there. 

Suppose you're reading https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Overview and you want to translate that to Turkish. You click the "Add translation" in the language drop-down . Takes you to https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Overview$locales and there you click in [`Türkçe (tr)`](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Overview$translate?tolocale=tr)
Make a tiny change just to enable the "Publish" button and then press to Publish: Internal Server Error!

We had a similar `IntegrityError` last week which was due to trying to do the first translation when in fact there was an existing translation (for your chosen locale). But that's not the problem this time. 

The **problem is: it's already been translated to a different slug**. See
```
>>> Document.all_objects.filter(locale='tr', parent=Document.objects.get(slug='Web/HTTP/Overview', locale='en-US'))
<QuerySet [<Document: /tr/docs/Web/HTTP/Genel_Bakis (HTTP'ye genel bakış)>]>
```
https://wiki.developer.mozilla.org/tr/docs/Web/HTTP/Genel_Bakis

And that page has been deleted with the reason `It was never fully translated from English.`

So the question is; **what should happen?**
If the document-translation you're about to submit, already exists, but has a different slug, what do you do? 
`https://developer.mozilla.org/tr/docs/Web/HTTP/Genel_Bakis` is a 302 redirect to `https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview`

The simplest solution is to simply avoid the soft-delete document and wipe it permanently. But if you do that, the old slug redirect will cease to work.

**Comment by atopal** [comment]
Didn't the old re-direct already cease to work because it is soft deleted?

I'm still left wondering why we have soft delete, seems like a rats nest of issues with almost zero benefit.

I think we should purge all soft deleted items.

**Comment by peterbe** [comment]
In https://discourse.mozilla.org/t/50-internal-server-error-while-saving/58804/2 it was reported that the URL they tried was: https://wiki.developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Publishing_your_website%24translate?tolocale=it

What I think is happening is that there is already a translated attempt at slug `Learn/Getting_started_with_the_web/Pubblicare_il_tuo_sito`  (in locale `it`) that exists as a soft-delete. 

```
>>> Document.objects.get(slug='Learn/Getting_started_with_the_web/Pubblicare_il_tuo_sito')
Traceback (most recent call last):
...
kuma.wiki.models.Document.DoesNotExist: Document matching query does not exist.
>>> Document.deleted_objects.get(slug='Learn/Getting_started_with_the_web/Pubblicare_il_tuo_sito')
<Document: /it/docs/Learn/Getting_started_with_the_web/Pubblicare_il_tuo_sito (Pubblicare il tuo sito)>
```

So, this time it's the soft-deletes that are blocking based on the *parent*.
